services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

volumes:
  postgres_data: